name: CI pipeline

on:
  push:
    branches: [cicd]


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: run test
        run: python -m tests/clean_test.py -v
          