name: CI pipeline

on:
  push:
    branches: [cicd]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.7"

      - name: install dependencies
        run: pip install -r requirements.txt
          
      - name: run test
        run: python -m tests/clean_test.py -v

